// backend/src/handlers/administrativo.rs
use axum::{extract::{Path, State}, http::StatusCode, Json};
use sqlx::PgPool;
use crate::models::*;

pub async fn criar_pessoa(State(p): State<PgPool>, Json(b): Json<CriarPessoaInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO pessoas (nome, cpf_cnpj, tipo_pessoa, email, perfil) VALUES ($1, $2, $3, $4, $5)").bind(&b.nome).bind(&b.cpf_cnpj).bind(&b.tipo_pessoa).bind(&b.email).bind(&b.perfil).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_pessoas(State(p): State<PgPool>) -> Result<Json<Vec<Pessoa>>, StatusCode> { Ok(Json(sqlx::query_as::<_, Pessoa>("SELECT id::text, nome, cpf_cnpj, tipo_pessoa, email, perfil FROM pessoas").fetch_all(&p).await.unwrap())) }
pub async fn publicar_noticia(State(p): State<PgPool>, Json(b): Json<CriarNoticiaInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO portal_noticias (titulo, resumo, conteudo) VALUES ($1, $2, $3)").bind(&b.titulo).bind(&b.resumo).bind(&b.conteudo).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_noticias(State(p): State<PgPool>) -> Result<Json<Vec<Noticia>>, StatusCode> { Ok(Json(sqlx::query_as::<_, Noticia>("SELECT id::text, titulo, resumo, conteudo, autor FROM portal_noticias ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn abrir_chamado(State(p): State<PgPool>, Json(b): Json<CriarChamadoInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO cidadao_chamados (cpf_cidadao, categoria, descricao, endereco) VALUES ($1, $2, $3, $4)").bind(&b.cpf_cidadao).bind(&b.categoria).bind(&b.descricao).bind(&b.endereco).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_chamados(State(p): State<PgPool>) -> Result<Json<Vec<ChamadoCidadao>>, StatusCode> { Ok(Json(sqlx::query_as::<_, ChamadoCidadao>("SELECT id::text, cpf_cidadao, categoria, descricao, endereco, status FROM cidadao_chamados ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn abrir_protocolo(State(p): State<PgPool>, Json(b): Json<CriarProtocoloInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO protocolos_processos (numero_protocolo, requerente, assunto, descricao) VALUES ($1, $2, $3, $4)").bind(&b.numero_protocolo).bind(&b.requerente).bind(&b.assunto).bind(&b.descricao).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_protocolos(State(p): State<PgPool>) -> Result<Json<Vec<Protocolo>>, StatusCode> { Ok(Json(sqlx::query_as::<_, Protocolo>("SELECT id::text, numero_protocolo, requerente, assunto, descricao, status FROM protocolos_processos ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }