// backend/src/handlers/financeiro.rs
use axum::{extract::{Path, State}, http::StatusCode, Json};
use sqlx::PgPool;
use crate::models::*;

pub async fn criar_empenho(State(p): State<PgPool>, Json(b): Json<CriarEmpenhoInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO empenhos (numero_empenho, valor, historico) VALUES ($1, $2, $3)").bind(&b.numero_empenho).bind(b.valor).bind(&b.historico).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_empenhos(State(p): State<PgPool>) -> Result<Json<Vec<Empenho>>, StatusCode> { Ok(Json(sqlx::query_as::<_, Empenho>("SELECT id::text, numero_empenho, valor::float8, historico, status FROM empenhos ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn liquidar_empenho(State(p): State<PgPool>, Path(id): Path<String>) -> Result<StatusCode, StatusCode> { sqlx::query("UPDATE empenhos SET status = 'LIQUIDADO' WHERE id = $1::uuid AND status = 'EMPENHADO'").bind(id).execute(&p).await.unwrap(); Ok(StatusCode::OK) }
pub async fn pagar_empenho(State(p): State<PgPool>, Path(id): Path<String>) -> Result<StatusCode, StatusCode> { sqlx::query("UPDATE empenhos SET status = 'PAGO' WHERE id = $1::uuid AND status = 'LIQUIDADO'").bind(id).execute(&p).await.unwrap(); Ok(StatusCode::OK) }
pub async fn criar_programa_ppa(State(p): State<PgPool>, Json(b): Json<CriarPpaInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO ppa_programas (nome, objetivo, teto_financeiro) VALUES ($1, $2, $3)").bind(&b.nome).bind(&b.objetivo).bind(b.teto_financeiro).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_programas_ppa(State(p): State<PgPool>) -> Result<Json<Vec<PpaPrograma>>, StatusCode> { Ok(Json(sqlx::query_as::<_, PpaPrograma>("SELECT id::text, nome, objetivo, teto_financeiro::float8 FROM ppa_programas ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn criar_diretriz_ldo(State(p): State<PgPool>, Json(b): Json<CriarLdoInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO ldo_diretrizes (ano, descricao, meta_fiscal) VALUES ($1, $2, $3)").bind(b.ano).bind(&b.descricao).bind(b.meta_fiscal).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_diretrizes_ldo(State(p): State<PgPool>) -> Result<Json<Vec<LdoDiretriz>>, StatusCode> { Ok(Json(sqlx::query_as::<_, LdoDiretriz>("SELECT id::text, ano, descricao, meta_fiscal::float8 FROM ldo_diretrizes ORDER BY ano DESC, criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn criar_dotacao_loa(State(p): State<PgPool>, Json(b): Json<CriarLoaInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO loa_dotacoes (codigo, descricao, saldo_inicial, saldo_atual) VALUES ($1, $2, $3, $3)").bind(&b.codigo).bind(&b.descricao).bind(b.saldo_inicial).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_dotacoes_loa(State(p): State<PgPool>) -> Result<Json<Vec<LoaDotacao>>, StatusCode> { Ok(Json(sqlx::query_as::<_, LoaDotacao>("SELECT id::text, codigo, descricao, saldo_inicial::float8, saldo_atual::float8 FROM loa_dotacoes ORDER BY codigo ASC").fetch_all(&p).await.unwrap())) }
pub async fn criar_convenio(State(p): State<PgPool>, Json(b): Json<CriarConvenioInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO convenios (numero_convenio, orgao_concedente, valor_global, valor_contrapartida) VALUES ($1, $2, $3, $4)").bind(&b.numero_convenio).bind(&b.orgao_concedente).bind(b.valor_global).bind(b.valor_contrapartida).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_convenios(State(p): State<PgPool>) -> Result<Json<Vec<Convenio>>, StatusCode> { Ok(Json(sqlx::query_as::<_, Convenio>("SELECT id::text, numero_convenio, orgao_concedente, valor_global::float8, valor_contrapartida::float8, status FROM convenios ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn criar_processo(State(p): State<PgPool>, Json(b): Json<CriarProcessoInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO processos_licitatorios (numero_processo, modalidade, objeto, valor_estimado) VALUES ($1, $2, $3, $4)").bind(&b.numero_processo).bind(&b.modalidade).bind(&b.objeto).bind(b.valor_estimado).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_processos(State(p): State<PgPool>) -> Result<Json<Vec<ProcessoLicitatorio>>, StatusCode> { Ok(Json(sqlx::query_as::<_, ProcessoLicitatorio>("SELECT id::text, numero_processo, modalidade, objeto, valor_estimado::float8, status FROM processos_licitatorios ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn criar_divida(State(p): State<PgPool>, Json(b): Json<CriarDividaInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO divida_ativa (contribuinte, numero_cda, valor_principal) VALUES ($1, $2, $3)").bind(&b.contribuinte).bind(&b.numero_cda).bind(b.valor_principal).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_dividas(State(p): State<PgPool>) -> Result<Json<Vec<Divida>>, StatusCode> { Ok(Json(sqlx::query_as::<_, Divida>("SELECT id::text, contribuinte, numero_cda, valor_principal::float8, status FROM divida_ativa ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn criar_lancamento(State(p): State<PgPool>, Json(b): Json<CriarLancamentoInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO tesouraria_lancamentos (conta_bancaria, tipo, valor, descricao) VALUES ($1, $2, $3, $4)").bind(&b.conta_bancaria).bind(&b.tipo).bind(b.valor).bind(&b.descricao).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_lancamentos(State(p): State<PgPool>) -> Result<Json<Vec<Lancamento>>, StatusCode> { Ok(Json(sqlx::query_as::<_, Lancamento>("SELECT id::text, conta_bancaria, tipo, valor::float8, descricao, conciliado FROM tesouraria_lancamentos ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn criar_alerta(State(p): State<PgPool>, Json(b): Json<CriarAlertaInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO controle_interno_alertas (titulo, nivel_severidade, modulo_origem, descricao) VALUES ($1, $2, $3, $4)").bind(&b.titulo).bind(&b.nivel_severidade).bind(&b.modulo_origem).bind(&b.descricao).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_alertas(State(p): State<PgPool>) -> Result<Json<Vec<AlertaAuditoria>>, StatusCode> { Ok(Json(sqlx::query_as::<_, AlertaAuditoria>("SELECT id::text, titulo, nivel_severidade, modulo_origem, descricao, resolvido FROM controle_interno_alertas ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn publicar_relatorio(State(p): State<PgPool>, Json(b): Json<CriarRelatorioInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO transparencia_relatorios (titulo, categoria, exercicio, link_arquivo) VALUES ($1, $2, $3, $4)").bind(&b.titulo).bind(&b.categoria).bind(b.exercicio).bind(&b.link_arquivo).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_relatorios(State(p): State<PgPool>) -> Result<Json<Vec<RelatorioTransparencia>>, StatusCode> { Ok(Json(sqlx::query_as::<_, RelatorioTransparencia>("SELECT id::text, titulo, categoria, exercicio, link_arquivo FROM transparencia_relatorios ORDER BY exercicio DESC, criado_em DESC").fetch_all(&p).await.unwrap())) }