// backend/src/handlers/operacional.rs
use axum::{extract::{Path, State}, http::StatusCode, Json};
use sqlx::PgPool;
use crate::models::*;

pub async fn criar_contracheque(State(p): State<PgPool>, Json(b): Json<CriarContrachequeInput>) -> Result<(StatusCode, Json<String>), StatusCode> { let l = b.salario_bruto - b.descontos; if l < 0.0 { return Err(StatusCode::BAD_REQUEST); } let r = sqlx::query("INSERT INTO folha_pagamento (servidor_nome, matricula, mes_referencia, salario_bruto, descontos, salario_liquido) VALUES ($1, $2, $3, $4, $5, $6)").bind(&b.servidor_nome).bind(&b.matricula).bind(&b.mes_referencia).bind(b.salario_bruto).bind(b.descontos).bind(l).execute(&p).await; match r { Ok(_) => Ok((StatusCode::CREATED, Json("Ok".to_string()))), Err(_) => Err(StatusCode::CONFLICT) } }
pub async fn listar_contracheques(State(p): State<PgPool>) -> Result<Json<Vec<Contracheque>>, StatusCode> { Ok(Json(sqlx::query_as::<_, Contracheque>("SELECT id::text, servidor_nome, matricula, mes_referencia, salario_bruto::float8, descontos::float8, salario_liquido::float8 FROM folha_pagamento ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn buscar_contracheques_servidor(State(p): State<PgPool>, Path(m): Path<String>) -> Result<Json<Vec<Contracheque>>, StatusCode> { Ok(Json(sqlx::query_as::<_, Contracheque>("SELECT id::text, servidor_nome, matricula, mes_referencia, salario_bruto::float8, descontos::float8, salario_liquido::float8 FROM folha_pagamento WHERE matricula = $1 ORDER BY mes_referencia DESC").bind(m).fetch_all(&p).await.unwrap())) }
pub async fn criar_solicitacao(State(p): State<PgPool>, Json(b): Json<CriarSolicitacaoInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO servidor_solicitacoes (matricula, tipo_solicitacao, data_inicio, data_fim) VALUES ($1, $2, $3::date, $4::date)").bind(&b.matricula).bind(&b.tipo_solicitacao).bind(&b.data_inicio).bind(&b.data_fim).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn buscar_solicitacoes_servidor(State(p): State<PgPool>, Path(m): Path<String>) -> Result<Json<Vec<SolicitacaoServidor>>, StatusCode> { Ok(Json(sqlx::query_as::<_, SolicitacaoServidor>("SELECT id::text, matricula, tipo_solicitacao, data_inicio::text, data_fim::text, status FROM servidor_solicitacoes WHERE matricula = $1 ORDER BY criado_em DESC").bind(m).fetch_all(&p).await.unwrap())) }
pub async fn gerar_evento_esocial(State(p): State<PgPool>, Json(b): Json<CriarEventoInput>) -> Result<(StatusCode, Json<String>), StatusCode> { let xml_mock = format!("<eSocial><evento tipo=\"{}\"><matricula>{}</matricula></evento></eSocial>", b.tipo_evento, b.matricula); sqlx::query("INSERT INTO esocial_eventos (matricula, tipo_evento, xml_gerado) VALUES ($1, $2, $3)").bind(&b.matricula).bind(&b.tipo_evento).bind(xml_mock).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_eventos_esocial(State(p): State<PgPool>) -> Result<Json<Vec<EventoEsocial>>, StatusCode> { Ok(Json(sqlx::query_as::<_, EventoEsocial>("SELECT id::text, matricula, tipo_evento, xml_gerado, status, protocolo_retorno FROM esocial_eventos ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn transmitir_evento_esocial(State(p): State<PgPool>, Path(id): Path<String>) -> Result<(StatusCode, Json<String>), StatusCode> { let p_mock = format!("PROT-GOVBR-{}", uuid::Uuid::new_v4().to_string().chars().take(8).collect::<String>().to_uppercase()); let r = sqlx::query("UPDATE esocial_eventos SET status = 'ENVIADO', protocolo_retorno = $1 WHERE id = $2::uuid AND status = 'AGUARDANDO_ENVIO'").bind(p_mock).bind(id).execute(&p).await.unwrap(); if r.rows_affected() == 0 { return Err(StatusCode::BAD_REQUEST); } Ok((StatusCode::OK, Json("Ok".to_string()))) }
pub async fn bater_ponto(State(p): State<PgPool>, Json(b): Json<CriarRegistroPontoInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO rh_ponto_eletronico (matricula, tipo_registro) VALUES ($1, $2)").bind(&b.matricula).bind(&b.tipo_registro).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_pontos(State(p): State<PgPool>) -> Result<Json<Vec<RegistroPonto>>, StatusCode> { Ok(Json(sqlx::query_as::<_, RegistroPonto>("SELECT id::text, matricula, tipo_registro, to_char(registrado_em, 'DD/MM/YYYY HH24:MI:SS') as registrado_em FROM rh_ponto_eletronico ORDER BY registrado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn criar_bem(State(p): State<PgPool>, Json(b): Json<CriarBemInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO bens_patrimoniais (codigo_tombamento, descricao, valor_aquisicao, setor_alocacao) VALUES ($1, $2, $3, $4)").bind(&b.codigo_tombamento).bind(&b.descricao).bind(b.valor_aquisicao).bind(&b.setor_alocacao).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_bens(State(p): State<PgPool>) -> Result<Json<Vec<BemPatrimonial>>, StatusCode> { Ok(Json(sqlx::query_as::<_, BemPatrimonial>("SELECT id::text, codigo_tombamento, descricao, valor_aquisicao::float8, setor_alocacao, situacao FROM bens_patrimoniais ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn criar_tributo(State(p): State<PgPool>, Json(b): Json<CriarTributoInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO tributos_lancamentos (contribuinte, tipo_tributo, exercicio, valor) VALUES ($1, $2, $3, $4)").bind(&b.contribuinte).bind(&b.tipo_tributo).bind(b.exercicio).bind(b.valor).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_tributos(State(p): State<PgPool>) -> Result<Json<Vec<Tributo>>, StatusCode> { Ok(Json(sqlx::query_as::<_, Tributo>("SELECT id::text, contribuinte, tipo_tributo, exercicio, valor::float8, status FROM tributos_lancamentos ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn emitir_nfse(State(p): State<PgPool>, Json(b): Json<CriarNotaFiscalInput>) -> Result<(StatusCode, Json<String>), StatusCode> { let v = b.valor_servico * (b.aliquota / 100.0); sqlx::query("INSERT INTO nfse_emissao (prestador_cnpj, tomador_cpf_cnpj, descricao_servico, valor_servico, aliquota, valor_issqn) VALUES ($1, $2, $3, $4, $5, $6)").bind(&b.prestador_cnpj).bind(&b.tomador_cpf_cnpj).bind(&b.descricao_servico).bind(b.valor_servico).bind(b.aliquota).bind(v).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_nfse(State(p): State<PgPool>) -> Result<Json<Vec<NotaFiscal>>, StatusCode> { Ok(Json(sqlx::query_as::<_, NotaFiscal>("SELECT id::text, numero_nota, prestador_cnpj, tomador_cpf_cnpj, descricao_servico, valor_servico::float8, aliquota::float8, valor_issqn::float8, status FROM nfse_emissao ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn registrar_leitura(State(p): State<PgPool>, Json(b): Json<CriarLeituraInput>) -> Result<(StatusCode, Json<String>), StatusCode> { let c = b.leitura_atual - b.leitura_anterior; if c < 0.0 { return Err(StatusCode::BAD_REQUEST); } let v = if c <= 10.0 { 35.0 } else { 35.0 + ((c - 10.0) * 5.0) }; sqlx::query("INSERT INTO agua_leituras (matricula_imovel, leitura_anterior, leitura_atual, consumo_m3, valor_fatura) VALUES ($1, $2, $3, $4, $5)").bind(&b.matricula_imovel).bind(b.leitura_anterior).bind(b.leitura_atual).bind(c).bind(v).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_leituras(State(p): State<PgPool>) -> Result<Json<Vec<LeituraAgua>>, StatusCode> { Ok(Json(sqlx::query_as::<_, LeituraAgua>("SELECT id::text, matricula_imovel, leitura_anterior::float8, leitura_atual::float8, consumo_m3::float8, valor_fatura::float8, status FROM agua_leituras ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }
pub async fn registrar_obito(State(p): State<PgPool>, Json(b): Json<CriarObitoInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO cemiterios_obitos (nome_falecido, cpf_falecido, data_obito, cemiterio, quadra_lote) VALUES ($1, $2, $3::date, $4, $5)").bind(&b.nome_falecido).bind(&b.cpf_falecido).bind(&b.data_obito).bind(&b.cemiterio).bind(&b.quadra_lote).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_obitos(State(p): State<PgPool>) -> Result<Json<Vec<RegistroObito>>, StatusCode> { Ok(Json(sqlx::query_as::<_, RegistroObito>("SELECT id::text, nome_falecido, cpf_falecido, to_char(data_obito, 'DD/MM/YYYY') as data_obito, cemiterio, quadra_lote, status FROM cemiterios_obitos ORDER BY data_obito DESC").fetch_all(&p).await.unwrap())) }
pub async fn registrar_veiculo(State(p): State<PgPool>, Json(b): Json<CriarVeiculoInput>) -> Result<(StatusCode, Json<String>), StatusCode> { sqlx::query("INSERT INTO frotas_veiculos (placa, modelo, departamento, quilometragem) VALUES ($1, $2, $3, $4)").bind(&b.placa).bind(&b.modelo).bind(&b.departamento).bind(b.quilometragem).execute(&p).await.unwrap(); Ok((StatusCode::CREATED, Json("Ok".to_string()))) }
pub async fn listar_veiculos(State(p): State<PgPool>) -> Result<Json<Vec<VeiculoFrota>>, StatusCode> { Ok(Json(sqlx::query_as::<_, VeiculoFrota>("SELECT id::text, placa, modelo, departamento, quilometragem::float8, status FROM frotas_veiculos ORDER BY criado_em DESC").fetch_all(&p).await.unwrap())) }